const DEFAULT_INGREDIENT_IMAGE = "images/ingredients/sample-ingredient.jpg";

const ingredientsData = [
    // --- PRESERVATIVES ---
    {
        name: "Sodium Metabisulfite (SMS / SMBS)",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E223",
        functionalClass: "1. Preservative, 2. Antioxidant, 3. Bleaching agent / Flour treatment agent",
        permittedCategories: "1. Dried fruits and vegetables, 2. Wines, ciders, 3. Crustaceans, 4. Fruit juices",
        mplDetails: "Dried fruits: 2000 mg/kg; Wines: 150-200 mg/L; Crustaceans: 50-150 mg/kg; FDA: GMP",
        rawMpl: "2000",
        unit: "mg/kg or mg/L",
        regulatorySource: "Codex GSFA, JECFA, EU 1333/2008, FDA CFR, Sri Lanka Regs",
        notes: "Allergen Labeling required if >10mg/kg. Prohibited in Vit B1 sources. Measured as Total SO2.",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Sodium Benzoate",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E211",
        functionalClass: "Preservative",
        permittedCategories: "1. Liquid egg product, 2. Vegetable pulp/preparations, 3. Semi-preserved fish, 4. Food supplements, 5. Fat spreads/flavoured milks, 6. Fruit preparations, 7. Water-based flavoured drinks, 8. Wines & vinegars",
        mplDetails: "Egg: 5000 mg/kg; Veg pulp: 3000 mg/kg; Fish/Supplements: 2000 mg/kg; Spreads/Fruit prep: 1000 mg/kg; Drinks: 250 mg/kg; Wines: 1000 mg/kg.",
        rawMpl: "1000",
        unit: "mg/kg (ppm) and % (FDA)",
        regulatorySource: "Codex GSFA, JECFA, EU 1333/2008, FDA CFR, Sri Lanka",
        notes: "Effective in acidic foods (pH < 4.5). Risk of benzene with ascorbic acid. ADI: 0–5 mg/kg bw.",
        lastUpdated: "2025"
    },
    {
        name: "Potassium Sorbate",
        image: "images/ingredients/potassium.jpeg",
        ins: "E202",
        functionalClass: "Preservative",
        permittedCategories: "1. Vegetable purees/spreads, 2. Water-based drinks, 3. Whey cheeses, 4. Fruit preparations/nuts/bakery, 5. Alcoholic beverages, 6. Meat products (surface)",
        mplDetails: "Veg prep: 1000 mg/kg; Drinks: 500 mg/kg; Cheese: 1000-3000 mg/kg; Fruit/Bakery: 1000-1500 mg/kg; Alcoholic: 200-500 mg/kg; Meat: 200 mg/kg.",
        rawMpl: "1000",
        unit: "mg/kg (ppm) / %",
        regulatorySource: "Codex GSFA, JECFA, EU 1333/2008, FDA CFR, Sri Lanka",
        notes: "Effective below pH 6.5. Regulated as group with Sorbic Acid (E200). ADI guides MPLs.",
        lastUpdated: "2025"
    },
    {
        name: "Sorbic Acid",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E200",
        functionalClass: "Preservative",
        permittedCategories: "1. Liquid egg, 2. Whey protein cheese, 3. Confectionery (non-chocolate), 4. Drinks, 5. Fruit juice, 6. Cooked fish, 7. Poultry/meat surface, 8. Baked goods, 9. Salads, 10. Sauces/Soups",
        mplDetails: "Liquid egg: 5000 mg/kg; Cheese: 3000 mg/kg; Confectionery/Salads: 1500 mg/kg; Drinks: 500 mg/kg; Bakery: up to 2000 mg/kg.",
        rawMpl: "2000",
        unit: "mg/kg / %",
        regulatorySource: "Codex GSFA, JECFA, EU 1333/2008, FDA CFR, Sri Lanka",
        notes: "Effective at acidic pH. Group ADI: 11 mg/kg bw/day. EU recently updated conditions.",
        lastUpdated: "2025"
    },
    {
        name: "Sodium Nitrite",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E250",
        functionalClass: "Preservative & colour-fixing agent",
        permittedCategories: "1. Cured non-heat treated meat, 2. Cured heat-treated meat, 3. Smoked/dried fish",
        mplDetails: "Codex: 80 mg/kg; EU: 80-100 mg/kg; FDA: 200 ppm in salmon.",
        rawMpl: "80",
        unit: "mg/kg / ppm",
        regulatorySource: "Codex GSFA, JECFA, EU, FDA, Sri Lanka",
        notes: "Nitrosamine Risk. Used with Ascorbic Acid to inhibit nitrosamines. Sold as curing salt mix.",
        lastUpdated: "2025"
    },
    {
        name: "Sodium Nitrate",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E251",
        functionalClass: "Preservative & colour-fixing agent",
        permittedCategories: "1. Cured non-heat treated meat, 2. Cured heat-treated meat, 3. Ripened cheese, 4. Pickled/cured fish",
        mplDetails: "Meat: 150-300 mg/kg; Cheese: 50-150 mg/kg; Fish (FDA): 500 ppm.",
        rawMpl: "150",
        unit: "mg/kg / ppm",
        regulatorySource: "Codex GSFA, JECFA, EU, FDA, Sri Lanka",
        notes: "Slow-acting; converts to Nitrite. Prevents 'late blowing' in cheeses.",
        lastUpdated: "2025"
    },
    {
        name: "Propionic Acid",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E280",
        functionalClass: "Preservative",
        permittedCategories: "1. Bakery wares, 2. Cheese, 3. Grain products, 4. Animal feeds",
        mplDetails: "Bakery wares: 1000-3000 mg/kg; Cheese: GMP up to 3000 mg/kg; FDA: GMP.",
        rawMpl: "2000",
        unit: "mg/kg / GMP",
        regulatorySource: "Codex, JECFA, EU, FDA, Sri Lanka",
        notes: "Strong pungent odor. Commonly used as salts (calcium/sodium propionate). ADI: 'not limited'.",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Sulfur Dioxide",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E220",
        functionalClass: "Preservative, Antioxidant, Bleaching agent",
        permittedCategories: "1. Dried fruits/veg, 2. Wines, ciders, 3. Fruit juices, 4. Herbs and spices",
        mplDetails: "Dried fruit: 2000 mg/kg; Wines: 150-350 mg/L; Juices: 50 mg/kg; FDA: 10-2000 ppm.",
        rawMpl: "2000",
        unit: "mg/kg / ppm",
        regulatorySource: "Codex, JECFA, EU, FDA, Sri Lanka",
        notes: "Severe allergen. Prohibited in Vit B1 sources and fresh produce. Measured as total SO2.",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Potassium Metabisulfite",
        ins: "E224",
        functionalClass: "Preservative, Antioxidant, Bleaching agent",
        permittedCategories: "1. Wines, ciders, meads, 2. Fruit juices, 3. Dried fruits, 4. Beer",
        mplDetails: "Wines: 150-400 mg/L; Dried fruit: 2000 mg/kg; Juices: 50 mg/kg; FDA: GMP.",
        rawMpl: "150",
        unit: "mg/kg / ppm",
        regulatorySource: "Codex, JECFA, EU, FDA, Sri Lanka",
        notes: "Preferred for winemaking to avoid sodium. Mandated allergen declaration if >10mg/kg.",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Sodium Bisulfite",
        ins: "E222",
        functionalClass: "Preservative, Antioxidant, Bleaching agent",
        permittedCategories: "1. Fruit preserves/jams, 2. Beverages, 3. Dried fruits, 4. Processed seafood",
        mplDetails: "Jams: 10-500 mg/kg; Beverages: 50-200 mg/L; Dried fruit: 2000 mg/kg; FDA: GMP.",
        rawMpl: "500",
        unit: "mg/kg / ppm",
        regulatorySource: "Codex, JECFA, EU, FDA, Sri Lanka",
        notes: "Prohibited on raw fresh produce and meats. Destroys Vitamin B1.",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Natamycin",
        ins: "E235",
        functionalClass: "Preservative / Antimycotic agent",
        permittedCategories: "1. Ripened/unripened cheese (surface), 2. Cured meats (surface)",
        mplDetails: "Cheese: 40 mg/kg (Codex) / 20 ppm (FDA) / 1 mg/dm² (EU); Meats: 20 mg/kg (Codex).",
        rawMpl: "40",
        unit: "mg/kg / ppm / mg/dm²",
        regulatorySource: "Codex, JECFA, EU, FDA, Sri Lanka",
        notes: "Targets only fungi. Insoluble, stays on surface. EU depth rule: <5mm penetration.",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Nisin",
        ins: "E234",
        functionalClass: "Preservative",
        permittedCategories: "1. Processed cheese, 2. Clotted cream, 3. Liquid egg, 4. Canned puddings",
        mplDetails: "Cheese/Egg: 12.5 mg/kg; Cream: 10 mg/kg; FDA: 250 ppm in cheese spreads.",
        rawMpl: "12.5",
        unit: "mg/kg / ppm",
        regulatorySource: "Codex, JECFA, EU, FDA, Sri Lanka",
        notes: "Bacteriocin from L. lactis. Stable at acidic pH and heat. No effect on yeast/molds.",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Parabens",
        ins: "E218, E219, E214, E215",
        functionalClass: "Preservative",
        permittedCategories: "1. Confectionery (non-chocolate), 2. Meat pastes/pâtés, 3. Marinated fish, 4. Liquid supplements",
        mplDetails: "Confectionery: 300-1000 mg/kg; Meat: up to 1000 mg/kg; FDA: 0.1% (1000 ppm).",
        rawMpl: "1000",
        unit: "mg/kg / %",
        regulatorySource: "Codex, JECFA, EU, FDA, Sri Lanka",
        notes: "EU banned Propylparaben (E216/217) in 2006. Industry shift towards paraben-free.",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Acetic Acid",
        ins: "E260",
        functionalClass: "Preservative, Acidity regulator",
        permittedCategories: "1. Pickles, 2. Condiments/Sauces, 3. Bakery, 4. Dairy (whey cheese)",
        mplDetails: "General: GMP (Quantum satis); Infants: 5000 mg/kg; FDA: 0.15% to 3.0%.",
        rawMpl: "GMP",
        unit: "GMP / %",
        regulatorySource: "Codex, JECFA, EU, FDA, Sri Lanka",
        notes: "Lowers pH. Naturally self-limiting due to odor/taste. ADI: 'not limited'.",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Lactic Acid",
        ins: "E270",
        functionalClass: "Acidity regulator, Preservative",
        permittedCategories: "1. Dairy, 2. Beverages, 3. Confectionery/Bakery, 4. Meat surface wash",
        mplDetails: "General: GMP (Quantum satis); Infants: GMP (L+ isomer only); FDA: 0.1% to 2.0%.",
        rawMpl: "GMP",
        unit: "GMP / %",
        regulatorySource: "Codex, JECFA, EU, FDA, Sri Lanka",
        notes: "Smooth tartness. I-isomer restriction for infants. Natural metabolic intermediate.",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Dimethyl Dicarbonate (DMDC)",
        ins: "E242",
        functionalClass: "Preservative / Cold Sterilant",
        permittedCategories: "1. Water-based flavoured drinks, 2. Wines/Ciders, 3. Liquid tea concentrates",
        mplDetails: "Beverages/Teas: 250 mg/kg; Wines: 200 mg/kg (Max added amount).",
        rawMpl: "250",
        unit: "mg/kg / mg/L",
        regulatorySource: "Codex, JECFA, EU, FDA, Sri Lanka",
        notes: "Hydrolyzes in 2-4 hours; zero residue. Toxic in pure form, needs closed-loop dosing.",
        lastUpdated: "2025 / 2026"
    },

    // --- ANTIOXIDANTS ---
    {
        name: "Ascorbic Acid / Vitamin C",
        ins: "E300",
        functionalClass: "Antioxidant, Colour retention, Flour treatment",
        permittedCategories: "1. Juices/Drinks, 2. Processed meats, 3. Canned fruits/veg, 4. Bakery",
        mplDetails: "General: GMP (Quantum satis); Infants: strictly regulated (e.g. 50 mg/kg in EU).",
        rawMpl: "GMP",
        unit: "GMP / %",
        regulatorySource: "Codex GSFA, JECFA, EU, FDA, Sri Lanka",
        notes: "Risk of benzene with Sodium Benzoate. Inhibits nitrosamines in cured meats.",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Sodium Ascorbate",
        ins: "E301",
        functionalClass: "Antioxidant, Colour retention",
        permittedCategories: "1. Cured meats, 2. Drinks, 3. Canned fruits/veg, 4. Bakery",
        mplDetails: "General: GMP (Quantum satis); FDA: GMP.",
        rawMpl: "GMP",
        unit: "GMP / %",
        regulatorySource: "Codex GSFA, JECFA, EU, FDA, Sri Lanka",
        notes: "Curing accelerator; non-acidic. Preferable where pH stability is required.",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Tocopherols / Vitamin E",
        ins: "E306-309",
        functionalClass: "Antioxidant",
        permittedCategories: "1. Oils/Fats, 2. Infants foods, 3. Cereals/Bakery, 4. Processed meats",
        mplDetails: "Fats/Oils: 300-500 mg/kg; Infants: strictly fixed limits; FDA: 0.01% to 0.05%.",
        rawMpl: "500",
        unit: "mg/kg / %",
        regulatorySource: "Codex GSFA, JECFA, EU, FDA, Sri Lanka",
        notes: "Free radical scavengers. Natural 'clean label' choice. Synergistic with Vitamin C.",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Butylated Hydroxyanisole (BHA)",
        ins: "E320",
        functionalClass: "Antioxidant",
        permittedCategories: "1. Edible fats/oils, 2. Chewing gum, 3. Snacks, 4. Processed meats/potatoes",
        mplDetails: "Fats: 100-200 mg/kg; Gum: 400 mg/kg; FDA: 0.02% of total fat.",
        rawMpl: "200",
        unit: "mg/kg / %",
        regulatorySource: "Codex GSFA, JECFA, EU 1333/2008, FDA, Sri Lanka",
        notes: "Synthetic phenolic. High heat stability. Synergistic with BHT. Under scrutiny (Prop 65).",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Butylated Hydroxytoluene (BHT)",
        ins: "E321",
        functionalClass: "Antioxidant",
        permittedCategories: "1. Fats/Oils, 2. Chewing gum, 3. Cereals/Snacks, 4. Meats/Potatoes",
        mplDetails: "Fats: 100-200 mg/kg; Snacks: 50 mg/kg; FDA: 0.02% of total fat.",
        rawMpl: "200",
        unit: "mg/kg / %",
        regulatorySource: "Codex, JECFA, EU, FDA, Sri Lanka",
        notes: "Prevents oxidative rancidity. Effective for baked/fried goods. Usually paired with BHA.",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Tert-butylhydroquinone (TBHQ)",
        ins: "E319",
        functionalClass: "Antioxidant",
        permittedCategories: "1. Frying oils, 2. Snacks/Crackers, 3. Processed meats/fish, 4. Popcorn/Noodles",
        mplDetails: "Fats/Oils: 200 mg/kg; FDA: 0.02% of total fat.",
        rawMpl: "200",
        unit: "mg/kg / %",
        regulatorySource: "Codex, JECFA, EU, FDA, Sri Lanka",
        notes: "Industry standard for deep-frying. Exceptional heat stability. Avoid with Propyl Gallate.",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Calcium Disodium EDTA",
        ins: "E385",
        functionalClass: "Sequestrant / Antioxidant / Preservative",
        permittedCategories: "1. Mayonnaise/Dressings, 2. Canned veg/legumes, 3. Canned seafood, 4. Fat spreads",
        mplDetails: "Mayonnaise: 75 mg/kg; Beans: 250 mg/kg; Seafood: 250-340 ppm; Spreads: 100 mg/kg.",
        rawMpl: "75",
        unit: "mg/kg / ppm",
        regulatorySource: "Codex, JECFA, EU, FDA, Sri Lanka",
        notes: "Chelating agent. Prevents benzene formation in drinks. Preferred over Disodium EDTA.",
        lastUpdated: "2025 / 2026"
    },

    // --- COLOURS ---
    {
        name: "Curcumin",
        ins: "E100",
        functionalClass: "Colour",
        permittedCategories: "Confectionery, Sauces, Fats & Oils",
        mplDetails: "GMP / 500 mg/kg",
        rawMpl: "500",
        unit: "mg/kg",
        regulatorySource: "GSFA Table 3, EU 1333/2008, SL Regs",
        notes: "Natural yellow (Turmeric); GMP in most categories.",
        lastUpdated: "14-Nov-25"
    },
    {
        name: "Riboflavins",
        ins: "E101",
        functionalClass: "Colour",
        permittedCategories: "Dairy products, Cereals, Bakery wares",
        mplDetails: "GMP / 300 mg/kg",
        rawMpl: "300",
        unit: "mg/kg",
        regulatorySource: "GSFA Table 3, FDA 21 CFR §73.450, SL Regs",
        notes: "Vitamin B2 source; Highly heat stable.",
        lastUpdated: "14-Nov-25"
    },
    {
        name: "Tartrazine",
        ins: "E102",
        functionalClass: "Colour",
        permittedCategories: "Beverages, Sweets, Snacks",
        mplDetails: "100 (SL) / 300 (GSFA)",
        rawMpl: "300",
        unit: "mg/kg",
        regulatorySource: "GSFA, FDA §74.705, SL Regs",
        notes: "Synthetic (Yellow 5); EU warning label required.",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Quinoline Yellow",
        ins: "E104",
        functionalClass: "Colour",
        permittedCategories: "Smoked fish, Seasonings, Edible ices",
        mplDetails: "200 (GSFA)",
        rawMpl: "200",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU, SL Regs",
        notes: "Banned in USA/Canada; Restricted in EU.",
        lastUpdated: "7-Jan-26"
    },
    {
        name: "Sunset Yellow FCF",
        ins: "E110",
        functionalClass: "Colour",
        permittedCategories: "Breakfast cereals, Dessert, Drinks",
        mplDetails: "100 (SL) / 300 (GSFA)",
        rawMpl: "300",
        unit: "mg/kg",
        regulatorySource: "GSFA, FDA §74.706, SL Regs",
        notes: "Synthetic (Yellow 6); Link to hyperactivity.",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Carmoisine",
        ins: "E122",
        functionalClass: "Colour",
        permittedCategories: "Jams & Jellies, Fruit fillings, Beverages",
        mplDetails: "100 (SL) / 500 (GSFA)",
        rawMpl: "500",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU, SL Regs",
        notes: "Azorubine; Synthetic red; Not permitted in US.",
        lastUpdated: "14-Jan-11"
    },
    {
        name: "Ponceau 4R",
        ins: "E124",
        functionalClass: "Colour",
        permittedCategories: "Ices & Sherbets, Processed fish, Pastries",
        mplDetails: "100 (SL) / 500 (GSFA)",
        rawMpl: "500",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU, SL Regs",
        notes: "Cochineal Red A; Synthetic azo dye.",
        lastUpdated: "14-Jan-11"
    },
    {
        name: "Erythrosine",
        ins: "E127",
        functionalClass: "Colour",
        permittedCategories: "Glacé cherries, Cocktail cherries",
        mplDetails: "100 (SL) / 200 (GSFA)",
        rawMpl: "200",
        unit: "mg/kg",
        regulatorySource: "GSFA, FDA §74.303, SL Regs",
        notes: "Synthetic (Red 3); Iodine containing colour.",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Allura Red AC",
        ins: "E129",
        functionalClass: "Colour",
        permittedCategories: "Seasonings, Cereals, Meat products",
        mplDetails: "100 (SL) / 300 (GSFA)",
        rawMpl: "300",
        unit: "mg/kg",
        regulatorySource: "GSFA, FDA §74.340, SL Regs",
        notes: "Synthetic (Red 40); Widely used in US.",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Indigotine",
        ins: "E132",
        functionalClass: "Colour",
        permittedCategories: "Bakery wares, Dairy analogues, Sweets",
        mplDetails: "100 (SL) / 300 (GSFA)",
        rawMpl: "300",
        unit: "mg/kg",
        regulatorySource: "GSFA, FDA §74.102, SL Regs",
        notes: "Indigo Carmine (Blue 2); Synthetic dye.",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Brilliant Blue FCF",
        ins: "E133",
        functionalClass: "Colour",
        permittedCategories: "Dairy desserts, Ices, Soft drinks",
        mplDetails: "100 (SL) / 100 (GSFA)",
        rawMpl: "100",
        unit: "mg/kg",
        regulatorySource: "GSFA, FDA §74.101, SL Regs",
        notes: "Synthetic (Blue 1); Very stable colour.",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Chlorophylls",
        ins: "E140",
        functionalClass: "Colour",
        permittedCategories: "Fats & Oils, Chewing gum, Fruit prep",
        mplDetails: "GMP",
        rawMpl: "GMP",
        unit: "-",
        regulatorySource: "GSFA Table 3, EU 1333/2008, SL Regs",
        notes: "Natural green from plants; Generally safe (GMP).",
        lastUpdated: "16-Jul-25"
    },
    {
        name: "Copper Chlorophyllins",
        ins: "E141",
        functionalClass: "Colour",
        permittedCategories: "Canned vegetables, Dairy products, Sauces",
        mplDetails: "500 (GSFA)",
        rawMpl: "500",
        unit: "mg/kg",
        regulatorySource: "GSFA, FDA §73.125, SL Regs",
        notes: "Na/K salts of copper complex; High light stability.",
        lastUpdated: "16-Jul-25"
    },
    {
        name: "Fast Green FCF",
        ins: "INS 143",
        functionalClass: "Colour",
        permittedCategories: "Edible ices, Beverages, Desserts",
        mplDetails: "100 (SL) / 100 (GSFA)",
        rawMpl: "100",
        unit: "mg/kg",
        regulatorySource: "GSFA, FDA §74.1203, SL Regs",
        notes: "FD&C Green No. 3; Banned in EU/UK.",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Plain Caramel (I)",
        ins: "E150a",
        functionalClass: "Colour",
        permittedCategories: "Soups & Sauces, Spirits, Bakery wares",
        mplDetails: "GMP",
        rawMpl: "GMP",
        unit: "-",
        regulatorySource: "GSFA Table 3, FDA §73.85, SL Regs",
        notes: "Class I Caramel; No ammonia/sulfite used.",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Ammonia Caramel (III)",
        ins: "E150c",
        functionalClass: "Colour",
        permittedCategories: "Beer, Gravy, Sauces",
        mplDetails: "50,000 (GSFA)",
        rawMpl: "50000",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU, SL Regs",
        notes: "Class III Caramel; Complex brown hue.",
        lastUpdated: "16-Jul-25"
    },
    {
        name: "Brilliant Black BN",
        ins: "E151",
        functionalClass: "Colour",
        permittedCategories: "Fish roe, Sauces, Sweets",
        mplDetails: "500 (GSFA)",
        rawMpl: "500",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU 1333/2008",
        notes: "Black PN; Synthetic; Not permitted in US.",
        lastUpdated: "16-Jul-25"
    },
    {
        name: "Vegetable Carbon",
        ins: "E153",
        functionalClass: "Colour",
        permittedCategories: "Cheese, Confectionery, Decorations",
        mplDetails: "GMP",
        rawMpl: "GMP",
        unit: "-",
        regulatorySource: "GSFA Table 3, EU 1333/2008",
        notes: "Activated charcoal; Banned in US as food colour.",
        lastUpdated: "16-Jul-25"
    },
    {
        name: "Brown HT",
        ins: "E155",
        functionalClass: "Colour",
        permittedCategories: "Chocolate cakes, Biscuits, Dairy",
        mplDetails: "50 (GSFA)",
        rawMpl: "50",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU 1333/2008",
        notes: "Chocolate Brown HT; Synthetic azo dye.",
        lastUpdated: "16-Jul-25"
    },
    {
        name: "Beta-Carotene (Veg)",
        ins: "E160a",
        functionalClass: "Colour",
        permittedCategories: "Margarine, Fats & Oils, Beverages",
        mplDetails: "1000 (GSFA)",
        rawMpl: "1000",
        unit: "mg/kg",
        regulatorySource: "GSFA, FDA §73.95, SL Regs",
        notes: "Provitamin A source; Natural orange/yellow.",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Annatto (Bixin)",
        ins: "E160b",
        functionalClass: "Colour",
        permittedCategories: "Cheese, Butter, Snacks",
        mplDetails: "1000 (GSFA)",
        rawMpl: "1000",
        unit: "mg/kg",
        regulatorySource: "GSFA, FDA §73.30, SL Regs",
        notes: "Natural seeds extract; Solvent-based extraction.",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Paprika Extract",
        ins: "E160c",
        functionalClass: "Colour",
        permittedCategories: "Snacks, Seasonings, Processed meat",
        mplDetails: "GMP",
        rawMpl: "GMP",
        unit: "-",
        regulatorySource: "GSFA Table 3, FDA §73.340, SL Regs",
        notes: "Natural red pigment; Contains Capsanthin.",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Lycopene (Synth)",
        ins: "E160d",
        functionalClass: "Colour",
        permittedCategories: "Sauces, Beverages, Desserts",
        mplDetails: "5000 (GSFA)",
        rawMpl: "5000",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU, FDA §73.585",
        notes: "Tomato-like red hue; High antioxidant capacity.",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Beetroot Red",
        ins: "E162",
        functionalClass: "Colour",
        permittedCategories: "Yogurt, Meat products, Ices",
        mplDetails: "GMP",
        rawMpl: "GMP",
        unit: "-",
        regulatorySource: "GSFA Table 3, FDA §73.40, SL Regs",
        notes: "Betanin from beets; pH and heat sensitive.",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Anthocyanins",
        ins: "E163",
        functionalClass: "Colour",
        permittedCategories: "Beverages, Fruit prep, Confectionery",
        mplDetails: "GMP",
        rawMpl: "GMP",
        unit: "-",
        regulatorySource: "GSFA Table 3, FDA §73.170, SL Regs",
        notes: "From grape skins/veg; pH sensitive (red-blue).",
        lastUpdated: "16-Mar-26"
    },

    // --- EMULSIFIERS ---
    {
        name: "Lecithin",
        ins: "E322",
        functionalClass: "Emulsifier, antioxidant",
        permittedCategories: "Chocolate, biscuit, bakery products, salad dressing",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex GSFA, FDA §184.1400, EU",
        notes: "Allergen warning (Soy/Egg). Minimal long-term high-dose data.",
        lastUpdated: "June 2025"
    },
    {
        name: "Mono and diglyceride of fatty acid",
        ins: "E471",
        functionalClass: "Emulsifier",
        permittedCategories: "Bakery, ice cream, margarine, cake, biscuit",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex GSFA, FDA (GRAS), EU",
        notes: "GRAS. Plant or animal derived. Rare sensitivity.",
        lastUpdated: "June 2025"
    },
    {
        name: "Polysorbates",
        ins: "E433 (E434,E435,E436)",
        functionalClass: "Emulsifier",
        permittedCategories: "Ice cream, baked product",
        mplDetails: "0.5 - 1.0 %",
        rawMpl: "1",
        unit: "%",
        regulatorySource: "Codex, FDA §172.840, EU",
        notes: "Synthetic origin. May cause mild digestive sensitivity.",
        lastUpdated: "June 2025"
    },
    {
        name: "Datem",
        ins: "E472e",
        functionalClass: "Emulsifier",
        permittedCategories: "Bread, cake, processed dough",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA, EU",
        notes: "Synthetic emulsifier with usage limits. Rare sensitivity.",
        lastUpdated: "June 2025"
    },
    {
        name: "Carrageenan",
        ins: "E407",
        functionalClass: "Emulsifier, thickener",
        permittedCategories: "Dairy products",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA, EU",
        notes: "Controversial (digestive concerns). EFSA opinion 2018.",
        lastUpdated: "2018 / 2025"
    },
    {
        name: "Guar gum",
        ins: "E412",
        functionalClass: "Emulsifier, thickener",
        permittedCategories: "Sauce, beverage, dessert",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA (GRAS), EU",
        notes: "May cause bloating in high amounts. Generally safe.",
        lastUpdated: "June 2025"
    },
    {
        name: "Gum arabic",
        ins: "E414",
        functionalClass: "Emulsifier, stabilizer",
        permittedCategories: "Confectionary beverages",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA (GRAS), EU",
        notes: "Rare allergic reactions. Generally well tolerated.",
        lastUpdated: "June 2025"
    },
    {
        name: "Xanthan gum",
        ins: "E415",
        functionalClass: "Emulsifier, thickener",
        permittedCategories: "Sauce, bakery products",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA (GRAS), EU",
        notes: "Possible digestive discomfort in excess. Safe usage levels.",
        lastUpdated: "June 2025"
    },
    {
        name: "Sodium stearoyl-2 lactylate",
        ins: "E481",
        functionalClass: "Emulsifier",
        permittedCategories: "Bakery products",
        mplDetails: "0.5 %",
        rawMpl: "0.5",
        unit: "%",
        regulatorySource: "Codex, FDA §172.846, EU",
        notes: "Approved emulsifier with limits. Rare sensitivity case.",
        lastUpdated: "June 2025"
    },
    {
        name: "Glucerol monostearate",
        ins: "E471",
        functionalClass: "Emulsifier",
        permittedCategories: "Bakery products, ice cream",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA (GRAS), EU",
        notes: "Generally safe. May be animal- or plant-derived.",
        lastUpdated: "June 2025"
    },
    {
        name: "Sucrose esters of fatty acids",
        ins: "E473",
        functionalClass: "Emulsifier",
        permittedCategories: "Bakery, dairy products",
        mplDetails: "1 %",
        rawMpl: "1",
        unit: "%",
        regulatorySource: "Codex, FDA (GRAS), EU",
        notes: "Regulated usage limits. Low toxicity.",
        lastUpdated: "June 2025"
    },
    {
        name: "Polyglycerol esters of fatty acids",
        ins: "E475",
        functionalClass: "Emulsifier",
        permittedCategories: "Chocolate, baked products",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA, EU",
        notes: "Approved within limits. Minimal toxicity concerns.",
        lastUpdated: "June 2025"
    },
    {
        name: "Sorbitan monostearate",
        ins: "E491",
        functionalClass: "Emulsifier",
        permittedCategories: "Bakery, confectionary",
        mplDetails: "0.5 %",
        rawMpl: "0.5",
        unit: "%",
        regulatorySource: "Codex, FDA §172.842, EU",
        notes: "Safe within limits. May cause mild digestive effects.",
        lastUpdated: "June 2025"
    },
    {
        name: "Sodium Caseinates",
        ins: "E469",
        functionalClass: "Emulsifier, stabilizer",
        permittedCategories: "Dairy products, processed foods",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA (GRAS), EU",
        notes: "Milk-derived allergen. Not suitable for dairy-free.",
        lastUpdated: "June 2025"
    },
    {
        name: "Ammonium phosphatides",
        ins: "E442",
        functionalClass: "Emulsifier",
        permittedCategories: "Chocolate, cocoa products",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA, EU",
        notes: "Approved emulsifier for chocolate. Usage limits apply.",
        lastUpdated: "June 2025"
    },
    {
        name: "Hydroxypropyl methyl cellulose",
        ins: "E464",
        functionalClass: "Emulsifier, thickener",
        permittedCategories: "Bakery, sauces",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA (GRAS), EU",
        notes: "Cellulose derivative. Generally safe.",
        lastUpdated: "June 2025"
    },
    {
        name: "Methyl cellulose",
        ins: "E461",
        functionalClass: "Emulsifier, thickener",
        permittedCategories: "Processed foods",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA (GRAS), EU",
        notes: "Safe at food levels. Possible bloating.",
        lastUpdated: "June 2025"
    },
    {
        name: "Stearyl tartrate",
        ins: "E483",
        functionalClass: "Emulsifier",
        permittedCategories: "Bakery, dough products",
        mplDetails: "0.5 %",
        rawMpl: "0.5",
        unit: "%",
        regulatorySource: "Codex, FDA, EU",
        notes: "Approved with limits. Minimal toxicity.",
        lastUpdated: "June 2025"
    },
    {
        name: "Gellan gum",
        ins: "E418",
        functionalClass: "Emulsifier, stabilizer",
        permittedCategories: "Beverages",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA (GRAS), EU",
        notes: "Generally safe. Rare digestive sensitivity.",
        lastUpdated: "June 2025"
    },
    {
        name: "Sucroglycerides",
        ins: "E474",
        functionalClass: "Emulsifier",
        permittedCategories: "Bakery, confectionary",
        mplDetails: "1 %",
        rawMpl: "1",
        unit: "%",
        regulatorySource: "Codex, FDA, EU",
        notes: "Low toxicity at permitted levels.",
        lastUpdated: "June 2025"
    },
    {
        name: "Propylene glycol esters of fatty acids",
        ins: "E477",
        functionalClass: "Emulsifier",
        permittedCategories: "Sauce",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA, EU",
        notes: "Regulated additive. Generally safe.",
        lastUpdated: "June 2025"
    },
    {
        name: "Calcium stearoyl lactylate",
        ins: "E482",
        functionalClass: "Emulsifier",
        permittedCategories: "Processed foods",
        mplDetails: "0.5 %",
        rawMpl: "0.5",
        unit: "%",
        regulatorySource: "Codex, FDA §172.844, EU",
        notes: "Approved with limits. Rare sensitivity.",
        lastUpdated: "June 2025"
    },
    {
        name: "Polyphosphate",
        ins: "E452",
        functionalClass: "Emulsifier, stabilizer",
        permittedCategories: "Processed meat, seafood",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA, EU",
        notes: "Excess may affect mineral balance. Regulated usage.",
        lastUpdated: "June 2025"
    },
    {
        name: "Polyglycerol polyricinoleate (PGPR)",
        ins: "E476",
        functionalClass: "Emulsifier",
        permittedCategories: "Chocolate, fat spread",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA, EU",
        notes: "Standard chocolate emulsifier. Limited concerns.",
        lastUpdated: "June 2025"
    },
    {
        name: "Propylene glycol alginate",
        ins: "E405",
        functionalClass: "Emulsifier, stabilizer",
        permittedCategories: "Sauce, beverage, bakery",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA (GRAS), EU",
        notes: "Approved additive. Generally safe within limits.",
        lastUpdated: "June 2025"
    },

    // --- ANTIOXIDANTS (CONT.) ---
    {
        name: "Citric acid",
        ins: "E330",
        functionalClass: "Antioxidant, Acidity regulator",
        permittedCategories: "Canned foods, beverages",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex GSFA, FDA §184.1033, EU",
        notes: "Generally safe. Excess may contribute to dental erosion.",
        lastUpdated: "June 2025"
    },
    {
        name: "Propyl gallate",
        ins: "E310",
        functionalClass: "Antioxidant",
        permittedCategories: "Snack foods, fats, oils",
        mplDetails: "0.01%",
        rawMpl: "0.01",
        unit: "%",
        regulatorySource: "Codex GSFA, FDA §172.615",
        notes: "Approved antioxidant. Rare sensitivity reported.",
        lastUpdated: "June 2025"
    },
    {
        name: "Ascorbyl palmitate",
        ins: "E304",
        functionalClass: "Antioxidant",
        permittedCategories: "Fats, oils",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex GSFA, FDA §182.3149, EU",
        notes: "Fat-soluble derivative of vitamin C. Generally safe.",
        lastUpdated: "June 2025"
    },
    {
        name: "Rosemary extract",
        ins: "E392",
        functionalClass: "Antioxidant",
        permittedCategories: "Vegetable Oils, margarine, meat",
        mplDetails: "0.01%",
        rawMpl: "0.01",
        unit: "%",
        regulatorySource: "Codex, FDA (GRAS), EU",
        notes: "Natural extract. Possible mild allergic reactions in some.",
        lastUpdated: "June 2025"
    },
    {
        name: "Erythorbic acid",
        ins: "E315",
        functionalClass: "Antioxidant",
        permittedCategories: "Meat, canned foods",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex GSFA, FDA §182.3045, EU",
        notes: "Structurally related to Vitamin C but not a vitamin.",
        lastUpdated: "June 2025"
    },
    {
        name: "Alpha tocopherol",
        ins: "E307",
        functionalClass: "Antioxidant",
        permittedCategories: "Vegetable oil",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex GSFA, FDA §182.8890, EU",
        notes: "Safe at typical levels. Form of Vitamin E.",
        lastUpdated: "June 2025"
    },
    {
        name: "Octyl gallate",
        ins: "E311",
        functionalClass: "Antioxidant",
        permittedCategories: "Fats, oil",
        mplDetails: "0.01%",
        rawMpl: "0.01",
        unit: "%",
        regulatorySource: "Codex GSFA, EU, FDA",
        notes: "Possible rare sensitivity reactions.",
        lastUpdated: "June 2025"
    },
    {
        name: "Dodecyl gallate",
        ins: "E312",
        functionalClass: "Antioxidant",
        permittedCategories: "Fat emulsions",
        mplDetails: "0.01%",
        rawMpl: "0.01",
        unit: "%",
        regulatorySource: "Codex GSFA, EU, FDA",
        notes: "Rare allergic reactions reported.",
        lastUpdated: "June 2025"
    },
    {
        name: "Tartaric acid",
        ins: "E334",
        functionalClass: "Antioxidant, acidulant",
        permittedCategories: "Fruit products, beverages",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex GSFA, FDA §184.1099, EU",
        notes: "Naturally occurring. High intake may cause discomfort.",
        lastUpdated: "June 2025"
    },

    // --- STABILIZERS ---
    {
        name: "Pectin",
        ins: "E440",
        functionalClass: "Stabilizer, Gelling agent",
        permittedCategories: "Jams, yoghurt, beverages",
        mplDetails: "GMP",
        rawMpl: "GMP",
        unit: "-",
        regulatorySource: "GSFA, EU 1333/2008, SL Regs",
        notes: "Natural (fruit-based). High degree of gelation.",
        lastUpdated: "14-Nov-25"
    },
    {
        name: "Agar",
        ins: "E406",
        functionalClass: "Stabilizer, Thickener",
        permittedCategories: "Desserts, jellies, dairy",
        mplDetails: "GMP",
        rawMpl: "GMP",
        unit: "-",
        regulatorySource: "GSFA, EU, SL",
        notes: "Seaweed origin. Strong gel formation.",
        lastUpdated: "16-Jul-25"
    },
    {
        name: "Carrageenan",
        ins: "E407",
        functionalClass: "Stabilizer, Thickener",
        permittedCategories: "Milk, ice cream, meat",
        mplDetails: "1000 mg/kg",
        rawMpl: "1000",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU, FDA",
        notes: "May cause sensitivity in excess.",
        lastUpdated: "16-Jul-25"
    },
    {
        name: "Locust Bean Gum",
        ins: "E410",
        functionalClass: "Stabilizer, Thickener",
        permittedCategories: "Ice cream, dairy, sauces",
        mplDetails: "5000 mg/kg",
        rawMpl: "5000",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU",
        notes: "Works synergistically with carrageenan.",
        lastUpdated: "16-Jul-25"
    },
    {
        name: "Xanthan Gum",
        ins: "E415",
        functionalClass: "Stabilizer, Thickener",
        permittedCategories: "Dressings, beverages, gluten-free",
        mplDetails: "1000 mg/kg",
        rawMpl: "1000",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU, FDA",
        notes: "Highly stable at wide pH and temperature ranges.",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Gum Arabic",
        ins: "E414",
        functionalClass: "Stabilizer, Emulsifier",
        permittedCategories: "Soft drinks, confectionery",
        mplDetails: "10000 mg/kg",
        rawMpl: "10000",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU",
        notes: "Acacia tree source. Excellent stabilizer.",
        lastUpdated: "16-Jul-25"
    },
    {
        name: "Sodium Alginate",
        ins: "E401",
        functionalClass: "Stabilizer, Gelling agent",
        permittedCategories: "Ice cream, sauces",
        mplDetails: "1000 mg/kg",
        rawMpl: "1000",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU",
        notes: "Forms gel with calcium ions.",
        lastUpdated: "16-Jul-25"
    },
    {
        name: "Gelatin",
        ins: "INS 441",
        functionalClass: "Stabilizer, Gelling agent",
        permittedCategories: "Desserts, dairy, confectionery",
        mplDetails: "GMP",
        rawMpl: "GMP",
        unit: "-",
        regulatorySource: "GSFA, FDA",
        notes: "Animal origin protein.",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Modified Starch",
        ins: "E1404–E1450",
        functionalClass: "Stabilizer, Thickener",
        permittedCategories: "Soups, sauces, dairy",
        mplDetails: "20,000 mg/kg",
        rawMpl: "20000",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU",
        notes: "Chemically modified starch for texture.",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Carboxymethyl Cellulose (CMC)",
        ins: "E466",
        functionalClass: "Stabilizer, Thickener",
        permittedCategories: "Ice cream, bakery, beverages",
        mplDetails: "10,000 mg/kg",
        rawMpl: "10000",
        unit: "mg/kg",
        regulatorySource: "GSFA, FDA",
        notes: "Prevents ice crystal formation in frozen foods.",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Konjac Gum",
        ins: "E425",
        functionalClass: "Stabilizer, Thickener",
        permittedCategories: "Noodles, jelly, vegan foods",
        mplDetails: "10,000 mg/kg",
        rawMpl: "10000",
        unit: "mg/kg",
        regulatorySource: "GSFA",
        notes: "High water absorption capacity.",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Calcium Alginate",
        ins: "E404",
        functionalClass: "Stabilizer, Gelling agent",
        permittedCategories: "Reformed foods, desserts",
        mplDetails: "1000 mg/kg",
        rawMpl: "1000",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU",
        notes: "Used in molecular gastronomy.",
        lastUpdated: "16-Jul-25"
    },
    {
        name: "Potassium Alginate",
        ins: "E402",
        functionalClass: "Stabilizer",
        permittedCategories: "Dairy, desserts",
        mplDetails: "1000 mg/kg",
        rawMpl: "1000",
        unit: "mg/kg",
        regulatorySource: "GSFA",
        notes: "Similar to sodium alginate.",
        lastUpdated: "16-Jul-25"
    },
    {
        name: "Tragacanth",
        ins: "E413",
        functionalClass: "Stabilizer, Thickener",
        permittedCategories: "Sauces, dressings",
        mplDetails: "10,000 mg/kg",
        rawMpl: "10000",
        unit: "mg/kg",
        regulatorySource: "GSFA",
        notes: "Natural gum, expensive.",
        lastUpdated: "7-Jan-26"
    },
    {
        name: "Tara Gum",
        ins: "E417",
        functionalClass: "Stabilizer",
        permittedCategories: "Dairy, desserts",
        mplDetails: "5000 mg/kg",
        rawMpl: "5000",
        unit: "mg/kg",
        regulatorySource: "GSFA",
        notes: "Alternative to guar gum.",
        lastUpdated: "7-Jan-26"
    },
    {
        name: "Microcrystalline Cellulose",
        ins: "E460",
        functionalClass: "Stabilizer, Bulking agent",
        permittedCategories: "Low-fat foods, dairy",
        mplDetails: "GMP",
        rawMpl: "GMP",
        unit: "-",
        regulatorySource: "GSFA, FDA",
        notes: "Fat replacer.",
        lastUpdated: "16-Mar-26"
    }
];
