const DEFAULT_INGREDIENT_IMAGE = "images/ingredients/sample-ingredient.jpg";

const ingredientsData = [
    // --- PRESERVATIVES ---
    {
        name: "Sodium Metabisulfite (SMS / SMBS)",
        image: "images/ingredients/SMBS.jpg",
        ins: "E223",
        functionalClass: "1. Preservative, 2. Antioxidant, 3. Bleaching agent / Flour treatment agent",
        permittedCategories: "1. Dried fruits and vegetables, 2. Wines, ciders, 3. Crustaceans, 4. Fruit juices",
        mplDetails: "Dried fruits: 2000 mg/kg; Wines: 150-200 mg/L; Crustaceans: 50-150 mg/kg; FDA: GMP",
        rawMpl: "2000",
        unit: "mg/kg or mg/L",
        regulatorySource: "Codex GSFA, JECFA, EU 1333/2008, FDA CFR, Sri Lanka Regs",
        notes: "Allergen Labeling required if >10mg/kg. Prohibited in Vit B1 sources. Measured as Total SO2.",
        regulatorySourceDetailed: "1. Codex Alimentarius (GSFA): Regulates permitted uses under INS 223, evaluated collectively with other sulfites. 2. FAO / WHO (JECFA): Provides the safety evaluation for the sulfite group. 3. EU Regulation (EC) No 1333/2008: Permitted under Annex II. 4. US FDA CFR: 21 CFR § 182.3766 (Categorized as GRAS when used under good manufacturing practices, subject to strict prohibitions). 5. Sri Lanka Food (Preservatives) Regulations: Governed under national schedules referencing international Codex limits for sulfites.",
        notesRestrictions: "1. Allergen Labeling (Critical): Mandatory declaration is required in almost all global jurisdictions (EU, FDA, Sri Lanka) if total residual sulfites exceed 10 mg/kg (or 10 ppm). 2. Vitamin B1 Prohibition: The FDA explicitly prohibits the use of sulfites in foods recognized as a major source of Vitamin B1 (thiamine) because it destroys the vitamin. It is also prohibited on raw fresh produce and fresh meats. 3. ADI / Safety: JECFA established a group Acceptable Daily Intake (ADI) of 0 - 0.7 mg/kg body weight per day (expressed as sulfur dioxide). 4. Measurement: Efficacy and regulatory compliance are measured analytically as Total SO2 rather than the physical weight of the powder added to the hopper.",
        sideEffects: "1. Allergic reactions: Can trigger severe sulfite sensitivity, particularly in individuals with asthma, leading to wheezing or chest tightness.",
        concerns: "1. Sulfite sensitivity: A significant portion of the population (especially those with asthma) cannot properly metabolize sulfites, leading to severe adverse reactions.",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Sodium Benzoate",
        image: "images/ingredients/Sodium-Benzoate.jpg",
        ins: "E211",
        functionalClass: "Preservative",
        permittedCategories: "1. Liquid egg product, 2. Vegetable pulp/preparations, 3. Semi-preserved fish, 4. Food supplements, 5. Fat spreads/flavoured milks, 6. Fruit preparations, 7. Water-based flavoured drinks, 8. Wines & vinegars",
        mplDetails: "Egg: 5000 mg/kg; Veg pulp: 3000 mg/kg; Fish/Supplements: 2000 mg/kg; Spreads/Fruit prep: 1000 mg/kg; Drinks: 250 mg/kg; Wines: 1000 mg/kg.",
        rawMpl: "1000",
        unit: "mg/kg (ppm) and % (FDA)",
        regulatorySource: "Codex GSFA, JECFA, EU 1333/2008, FDA CFR, Sri Lanka",
        notes: "Effective in acidic foods (pH < 4.5). Risk of benzene with ascorbic acid. ADI: 0–5 mg/kg bw.",
        regulatorySourceDetailed: "1.Codex Alimentarius (GSFA): International food additive standard listing E 211 and permitted use levels in specific food categories (48ᵗʰ CAC, 2025 update). 2.FAO/WHO (JECFA): Scientific evaluations underpin Codex provisions and safety assessments (e.g., ADI). 3.EU (EFSA / Regulation 1333/2008): E 211 is authorised as a food additive under EU law, with detailed conditions of use and MPLs set in Annex II; searchable EU food‑additive portal lists conditions and notes. 4.US FDA (CFR): Sodium benzoate is GRAS and permitted in food under 21 CFR § 184.1733, with current usage resulting in a maximum level of 0.1 % in foods as part of good manufacturing practice. 5.Sri Lanka Food Additives Regulations: National lists reference Codex standards for permitted additives and MPLs; no widely‑published separate national MPL table exists but Sri Lanka uses Codex‑derived limits and requires compliance with specifications and labeling.",
        notesRestrictions: "1.Functional constraints: E 211 acts as a preservative primarily in acidic foods (pH < 4.5), where benzoate is effective as benzoic acid. 2.Group classification: In Codex, sodium benzoate is part of the benzoates group along with benzoic acid and other benzoate salts; group MPLs often apply to the total content of all participating benzoates. 3.FDA/GRAS: FDA lists it as GRAS when used at levels not exceeding good manufacturing practice; current industry practice is ~0.1 % in food. 4.Potential interaction: Benzoates + ascorbic acid under certain conditions may form benzene, a carcinogen; risk management guidance exists for beverage formulations. 5.Labeling: Under EU and many national regulations, E 211 must be declared on labels with its functional class (preservative). 6.ADI: The Acceptable Daily Intake for benzoic acid and its salts is established by JECFA and used as a basis for setting MPLs (common ADI is 0–5 mg/kg bw for benzoates).",
        sideEffects: "1.Allergic Reactions: Can trigger localized skin irritation, hives (urticaria), redness, or itching in sensitive individuals.",
        concerns: "1.Benzene Formation: When combined with Vitamin C (Ascorbic Acid) in drinks, it can chemically react to form benzene—a known carcinogen.",
        lastUpdated: "2025"
    },
    {
        name: "Potassium Sorbate",
        image: "images/ingredients/Potassium-Sorbate.jpg",
        ins: "E202",
        functionalClass: "Preservative",
        permittedCategories: "1. Vegetable purees/spreads, 2. Water-based drinks, 3. Whey cheeses, 4. Fruit preparations/nuts/bakery, 5. Alcoholic beverages, 6. Meat products (surface)",
        mplDetails: "Veg prep: 1000 mg/kg; Drinks: 500 mg/kg; Cheese: 1000-3000 mg/kg; Fruit/Bakery: 1000-1500 mg/kg; Alcoholic: 200-500 mg/kg; Meat: 200 mg/kg.",
        rawMpl: "1000",
        unit: "mg/kg (ppm) / %",
        regulatorySource: "Codex GSFA, JECFA, EU 1333/2008, FDA CFR, Sri Lanka",
        notes: "Effective below pH 6.5. Regulated as group with Sorbic Acid (E200). ADI guides MPLs.",
        regulatorySourceDetailed: "1.Codex Alimentarius (GSFA): International standard listing permitted uses and MPLs; updated online through the 48ᵗʰ Codex Commission session (2025). 2.FAO/WHO JECFA: Scientific evaluation underpins ADI and safety (preservative group). 3.EU Regulation 1333/2008: EU additive law with Annex II conditions of use; EFSA re‑evaluations inform regulatory decisions (e.g., 2019 opinion). 4.FDA CFR: In the US, potassium sorbate is GRAS when used consistent with GMP. 5.Sri Lanka Food Preservatives Regulations 2019: Preservatives including sorbates are listed with food categories and limits (outlined in schedule documents).",
        notesRestrictions: "1.Group regulation: Potassium sorbate and sorbic acid (E200) are often regulated as a group (E200–E202) in Codex and EU frameworks; MPL applies to combined total expressed as sorbic acid. 2.Effectiveness depends on pH: Sorbates are most effective in acidic environments (below ~pH 6.5). 3.Recent EU extension: Newly permitted use in non‑heat‑treated plant‑based mousses at 500 mg/kg. 4.Safety evaluations: EFSA re‑evaluated sorbic acid and its salts (including E202); updated opinions guide EU regulatory positions. 5.Labeling: In EU and many countries, E202 must be declared on ingredient lists with functional class (preservative). 6.ADI/safety: JECFA/EFSA ADIs guide MPLs to ensure consumer exposure remains below safe levels.",
        sideEffects: "1.Contact Dermatitis: Can cause skin irritation, redness, burning, or hives, particularly when used in cosmetics, lotions, or wipes on sensitive skin.",
        concerns: "1.Pseudoallergy: While actual internal allergic reactions are very rare, it can trigger non-allergic hypersensitivity responses in individuals prone to eczema or skin conditions.",
        lastUpdated: "2025"
    },
    {
        name: "Sorbic Acid",
        image: "images/ingredients/Sorbic Acid.jpg",
        ins: "E200",
        functionalClass: "Preservative",
        permittedCategories: "1. Liquid egg, 2. Whey protein cheese, 3. Confectionery (non-chocolate), 4. Drinks, 5. Fruit juice, 6. Cooked fish, 7. Poultry/meat surface, 8. Baked goods, 9. Salads, 10. Sauces/Soups",
        mplDetails: "Liquid egg: 5000 mg/kg; Cheese: 3000 mg/kg; Confectionery/Salads: 1500 mg/kg; Drinks: 500 mg/kg; Bakery: up to 2000 mg/kg.",
        rawMpl: "2000",
        unit: "mg/kg / %",
        regulatorySource: "Codex GSFA, JECFA, EU 1333/2008, FDA CFR, Sri Lanka",
        notes: "Effective at acidic pH. Group ADI: 11 mg/kg bw/day. EU recently updated conditions.",
        regulatorySourceDetailed: "1.Codex Alimentarius (GSFA) International additive standard; functional class and MPLs for E 200; updated to 48ᵗʰ Codex Commission session (2025). 2.FAO/WHO (JECFA) Safety evaluations and ADI basis for inclusion in GSFA. 3.EU Regulation (EC) 1333/2008 Lists permitted additives and MPL conditions; regularly updated with implementing regulations. 4.FDA CFR (21 CFR § 182.3089) Sorbic acid is GRAS under GMP conditions in foods. 5.Sri Lanka Food (Preservatives) Regulations 2019 National schedule including E 200 as permitted preservative.",
        notesRestrictions: "1.Functional grouping: In Codex and EU frameworks, sorbic acid (E 200) is often listed with sorbate salts (E 201–E 203) and their combined total is expressed as sorbic acid for MPL calculations. 2.Effectiveness: Sorbic acid is more effective at acidic pH (< 6.5) and is widely used in foods with low pH. 3.Safety evaluations: EFSA and JECFA have evaluated sorbic acid; EFSA updated a group ADI of 11 mg/kg bw/day for sorbic acid and potassium sorbate based on re‑evaluation. (See recent EU regulatory texts).  4.EU reductions & changes: EU has updated additive specifications, including reductions in heavy metal limits and new authorisations (e.g., fruit‑flavoured desserts at 1000 mg/kg and plant‑based mousses at 500 mg/kg). 5.FDA: As GRAS, sorbic acid must be used according to good manufacturing practice; specific uses include cheeses, fruit products, and margarine at customary industry levels.                                                                                                   6.Labeling: In EU and many national regulations, E 200 must be declared with its name and functional class (preservative) on food labels.    ",
        sideEffects: "1.Contact Dermatitis: Direct skin contact from cosmetics, topical creams, or wet wipes frequently causes localized redness, itching, burning, or a stinging sensation.",
        concerns: "1.Hypersensitivity Reactions: It is a well-known skin sensitizer. Individuals with pre-existing skin conditions like eczema or psoriasis are at a much higher risk of developing a reaction.",
        lastUpdated: "2025"
    },
    {
        name: "Sodium Nitrite",
        image: "images/ingredients/sodium-nitrites.jpg",
        ins: "E250",
        functionalClass: "Preservative & colour-fixing agent",
        permittedCategories: "1. Cured non-heat treated meat, 2. Cured heat-treated meat, 3. Smoked/dried fish",
        mplDetails: "Codex: 80 mg/kg; EU: 80-100 mg/kg; FDA: 200 ppm in salmon.",
        rawMpl: "80",
        unit: "mg/kg / ppm",
        regulatorySource: "Codex GSFA, JECFA, EU, FDA, Sri Lanka",
        notes: "Nitrosamine Risk. Used with Ascorbic Acid to inhibit nitrosamines. Sold as curing salt mix.",
        regulatorySourceDetailed: "1. Codex Alimentarius (GSFA): International standard listing permitted uses and MPLs for INS 250; limits usually expressed as residual nitrite. 2. FAO/WHO JECFA: Scientific evaluation establishes safety limits (ADI). 3. EU Regulation 1333/2008 & EFSA: Permitted in Annex II. Recently amended by Reg (EU) 2023/2108 to significantly lower maximum limits to reduce consumer exposure to nitrosamines. 4. US FDA CFR / USDA FSIS: 21 CFR § 172.175 (max 200 ppm in smoked salmon/sablefish/shad); USDA regulates meat at typically 120-156 ppm added nitrite. 5. Sri Lanka Food (Preservatives) Regulations 2019: Recognizes nitrites for cured meats, leaning on Codex safety guidelines.",
        notesRestrictions: "1. Nitrosamine Risk: Nitrites can react with secondary amines in the food or stomach to form nitrosamines, which are probable carcinogens. Regulatory limits are strictly enforced to balance botulism prevention with cancer risk. 2. ADI/Safety: JECFA established an Acceptable Daily Intake (ADI) of 0.07 mg/kg body weight/day. 3. Synergistic Ingredients: Often mandated or recommended to be used alongside Ascorbic Acid or Sodium Ascorbate (E300/E301) which act to inhibit the formation of nitrosamines. 4. Pre-mixing: In many jurisdictions, it must be sold pre-mixed with sodium chloride (curing salt) at low concentrations (e.g., 6%) to prevent lethal accidental overdoses in manufacturing facilities.",
        sideEffects: "1.Methemoglobinemia: High intake can oxidize the iron in your hemoglobin, turning it into methemoglobin. This reduces the blood's ability to carry oxygen, leading to headaches, fatigue, dizziness, or a bluish skin tint (cyanosis).",
        concerns: "1.Nitrosamine Formation: When subjected to high heat (like frying bacon) or combined with strong stomach acids, nitrites react with amines in meat to form nitrosamines, which are highly potent, Group 1 carcinogens.",
        lastUpdated: "2025"
    },
    {
        name: "Sodium Nitrate",
        image: "images/ingredients/sodium-nitrate.jpg",
        ins: "E251",
        functionalClass: "Preservative & colour-fixing agent",
        permittedCategories: "1. Cured non-heat treated meat, 2. Cured heat-treated meat, 3. Ripened cheese, 4. Pickled/cured fish",
        mplDetails: "Meat: 150-300 mg/kg; Cheese: 50-150 mg/kg; Fish (FDA): 500 ppm.",
        rawMpl: "150",
        unit: "mg/kg / ppm",
        regulatorySource: "Codex GSFA, JECFA, EU, FDA, Sri Lanka",
        notes: "Slow-acting; converts to Nitrite. Prevents 'late blowing' in cheeses.",
        regulatorySourceDetailed: "1. Codex Alimentarius (GSFA): Regulates permitted uses and maximum levels (INS 251). 2. FAO/WHO JECFA: Scientific evaluation for Acceptable Daily Intake (ADI). 3. EU Regulation 1333/2008: Permitted in Annex II. Substantially amended by Regulation (EU) 2023/2108, which lowers limits to reduce nitrosamine exposure. 4. US FDA CFR: 21 CFR 172.170 limits sodium nitrate to 500 ppm in specific smoked/cured fish and home meat-curing preparations. 5. Sri Lanka Food (Preservatives) Regulations: Governed under the national schedules referencing international Codex limits.",
        notesRestrictions: "1. Conversion to Nitrite: Nitrate itself is relatively inert as a preservative; it relies on bacterial reduction into nitrite over time, making it ideal for long-curing processes. 2. Nitrosamine Risk: Because it converts to nitrite, it carries the same risk of forming carcinogenic nitrosamines when exposed to high heat. 3. ADI/Safety: JECFA and EFSA have established an ADI of 3.7 mg nitrate ion/kg body weight per day.",
        sideEffects: "1.Vasodilation Headaches: As it converts to nitrites and eventually nitric oxide, it relaxes and widens blood vessels. This can trigger throbbing headaches, dizziness, or facial flushing.",
        concerns: "1.Indirect Carcinogenicity: Once converted to nitrites in the body, it can react with amino acids (especially under high heat or in stomach acid) to form nitrosamines, which are strongly linked to colorectal and gastric cancers.",
        lastUpdated: "2025"
    },
    {
        name: "Propionic Acid",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E280",
        functionalClass: "Preservative",
        permittedCategories: "1. Bakery wares, 2. Cheese, 3. Grain products, 4. Animal feeds",
        mplDetails: "Bakery wares: 1000-3000 mg/kg; Cheese: GMP up to 3000 mg/kg; FDA: GMP.",
        rawMpl: "2000",
        unit: "mg/kg / GMP",
        regulatorySource: "Codex, JECFA, EU, FDA, Sri Lanka",
        notes: "Strong pungent odor. Commonly used as salts (calcium/sodium propionate). ADI: 'not limited'.",
        regulatorySourceDetailed: "1. Codex Alimentarius (GSFA): Regulates permitted uses and maximum levels (often grouping INS 280 with its salts 281-283). 2. FAO / WHO (JECFA): Provides the scientific safety evaluation and establishes the ADI. 3. EU Regulation (EC) No 1333/2008: Permitted under Annex II. 4. US FDA CFR: 21 CFR § 184.1081 (Categorized as Generally Recognized as Safe - GRAS when used under good manufacturing practices). 5. Sri Lanka Food (Preservatives) Regulations: Listed in national schedules referencing international Codex limits",
        notesRestrictions: "1. Sensory & Physical Impact: In its pure form, propionic acid is a highly corrosive liquid with a strong, pungent, rancid odor. Due to this aggressive physical state, manufacturers more commonly use its dry salts (calcium or sodium propionate) for easier handling. 2. Natural Occurrence: It is naturally produced by bacteria (Propionibacterium) during the fermentation of certain foods, such as Swiss cheese, which can naturally contain up to 1% propionic acid.",
        sideEffects: "1.Severe Local Irritation: Direct contact with liquid or concentrated vapor causes painful skin burns, severe eye damage, and irritation of the mucous membranes.",
        concerns: "1.Neurological & Behavioral Links: Animal studies have investigated high doses of propionic acid for its ability to induce temporary autism-like behaviors and neuroinflammation, sparking research into how excess dietary intake might affect neurodevelopment.",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Sulfur Dioxide",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E220",
        functionalClass: "Preservative, Antioxidant, Bleaching agent",
        permittedCategories: "1. Dried fruits/veg, 2. Wines, ciders, 3. Fruit juices, 4. Herbs and spices",
        mplDetails: "Dried fruit: 2000 mg/kg; Wines: 150-350 mg/L; Juices: 50 mg/kg; FDA: 10-2000 ppm.",
        rawMpl: "2000",
        unit: "mg/kg / ppm",
        regulatorySource: "Codex, JECFA, EU, FDA, Sri Lanka",
        notes: "Severe allergen. Prohibited in Vit B1 sources and fresh produce. Measured as total SO2.",
        regulatorySourceDetailed: "will 1. Codex Alimentarius (GSFA): Regulates permitted uses and maximum levels under INS 220 (typically evaluated as a group under SULFITES). 2. FAO / WHO (JECFA): Provides the foundational scientific safety evaluation for the sulfite group. 3. EU Regulation (EC) No 1333/2008: Permitted under Annex II. 4. US FDA CFR: 21 CFR § 182.3862 (Categorized as GRAS when used under good manufacturing practices, subject to strict prohibitions). 5. Sri Lanka Food (Preservatives) Regulations: Governed under national schedules referencing international Codex limits.be added soon...",
        notesRestrictions: "1. Allergen Labeling (Critical): Due to severe sensitivity and asthma risks in some populations, mandatory allergen declaration is required in almost all jurisdictions (EU, FDA, Codex) if total residual sulfites exceed 10 mg/kg (or 10 ppm). 2. Vitamin B1 Prohibition: The FDA explicitly prohibits the use of sulfur dioxide in foods recognized as a major source of Vitamin B1 (thiamine) because it destroys the vitamin. It is also prohibited on fresh produce and meats. 3. ADI / Safety: JECFA established a group Acceptable Daily Intake (ADI) of 0 – 0.7 mg/kg body weight per day (expressed as sulfur dioxide). 4. Group Measurement: It is almost always regulated and measured collectively alongside its sulfite salts (E221–E228) and reported on spec sheets as total SO2 or residual SO2.",
        sideEffects: "1.Severe Bronchoconstriction: Immediate inhalation or ingestion can cause narrowing of the airways, leading to wheezing, chest tightness, coughing, and labored breathing.",
        concerns: "1.The Sulfite/Asthma Link: Sulfur dioxide is highly hazardous to individuals with asthma. Exposure to even minuscule amounts can trigger rapid, severe, and potentially life-threatening asthmatic attacks.",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Potassium Metabisulfite",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E224",
        functionalClass: "Preservative, Antioxidant, Bleaching agent",
        permittedCategories: "1. Wines, ciders, meads, 2. Fruit juices, 3. Dried fruits, 4. Beer",
        mplDetails: "Wines: 150-400 mg/L; Dried fruit: 2000 mg/kg; Juices: 50 mg/kg; FDA: GMP.",
        rawMpl: "150",
        unit: "mg/kg / ppm",
        regulatorySource: "Codex, JECFA, EU, FDA, Sri Lanka",
        notes: "Preferred for winemaking to avoid sodium. Mandated allergen declaration if >10mg/kg.",
        regulatorySourceDetailed: "1. Codex Alimentarius (GSFA): Regulates permitted uses under INS 224, evaluated collectively with the sulfite group. 2. FAO / WHO (JECFA): Provides the foundational safety evaluation for all sulfites. 3. EU Regulation (EC) No 1333/2008: Permitted under Annex II. 4. US FDA CFR: 21 CFR § 182.3637 (Categorized as GRAS when used under good manufacturing practices, subject to strict prohibitions). 5. Sri Lanka Food (Preservatives) Regulations: Governed under national schedules referencing international Codex limits for sulfites.",
        notesRestrictions: "1. Allergen Labeling (Critical): Mandatory declaration is required across almost all jurisdictions (EU, FDA, Sri Lanka) if total residual sulfites exceed 10 mg/kg (or 10 ppm). 2. Potassium vs. Sodium: Preferred over E223 in beverages (like wine) to avoid sodium contribution, which can alter taste and dietary profiles. 3. Vitamin B1 Prohibition: The FDA strictly prohibits the use of sulfites in foods recognized as a major source of Vitamin B1 (thiamine) as well as on raw fresh produce and fresh meats. 4. ADI / Safety: JECFA established a group Acceptable Daily Intake (ADI) of 0 – 0.7 mg/kg body weight per day (expressed as total sulfur dioxide).",
        sideEffects: "1.Acute Bronchospasms: Ingestion or inhalation of liberated gas causes immediate airway constriction, resulting in severe wheezing, chest tightness, coughing, and shortness of breath.",
        concerns: "1.Hyper-Reactivity in Asthmatics: It is highly dangerous for people with asthma. Even trace amounts can trigger rapid, debilitating, or life-threatening asthma attacks.",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Sodium Bisulfite",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E222",
        functionalClass: "Preservative, Antioxidant, Bleaching agent",
        permittedCategories: "1. Fruit preserves/jams, 2. Beverages, 3. Dried fruits, 4. Processed seafood",
        mplDetails: "Jams: 10-500 mg/kg; Beverages: 50-200 mg/L; Dried fruit: 2000 mg/kg; FDA: GMP.",
        rawMpl: "500",
        unit: "mg/kg / ppm",
        regulatorySource: "Codex, JECFA, EU, FDA, Sri Lanka",
        notes: "Prohibited on raw fresh produce and meats. Destroys Vitamin B1.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Natamycin",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E235",
        functionalClass: "Preservative / Antimycotic agent",
        permittedCategories: "1. Ripened/unripened cheese (surface), 2. Cured meats (surface)",
        mplDetails: "Cheese: 40 mg/kg (Codex) / 20 ppm (FDA) / 1 mg/dm² (EU); Meats: 20 mg/kg (Codex).",
        rawMpl: "40",
        unit: "mg/kg / ppm / mg/dm²",
        regulatorySource: "Codex, JECFA, EU, FDA, Sri Lanka",
        notes: "Targets only fungi. Insoluble, stays on surface. EU depth rule: <5mm penetration.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Nisin",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E234",
        functionalClass: "Preservative",
        permittedCategories: "1. Processed cheese, 2. Clotted cream, 3. Liquid egg, 4. Canned puddings",
        mplDetails: "Cheese/Egg: 12.5 mg/kg; Cream: 10 mg/kg; FDA: 250 ppm in cheese spreads.",
        rawMpl: "12.5",
        unit: "mg/kg / ppm",
        regulatorySource: "Codex, JECFA, EU, FDA, Sri Lanka",
        notes: "Bacteriocin from L. lactis. Stable at acidic pH and heat. No effect on yeast/molds.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Parabens",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E218, E219, E214, E215",
        functionalClass: "Preservative",
        permittedCategories: "1. Confectionery (non-chocolate), 2. Meat pastes/pâtés, 3. Marinated fish, 4. Liquid supplements",
        mplDetails: "Confectionery: 300-1000 mg/kg; Meat: up to 1000 mg/kg; FDA: 0.1% (1000 ppm).",
        rawMpl: "1000",
        unit: "mg/kg / %",
        regulatorySource: "Codex, JECFA, EU, FDA, Sri Lanka",
        notes: "EU banned Propylparaben (E216/217) in 2006. Industry shift towards paraben-free.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Acetic Acid",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E260",
        functionalClass: "Preservative, Acidity regulator",
        permittedCategories: "1. Pickles, 2. Condiments/Sauces, 3. Bakery, 4. Dairy (whey cheese)",
        mplDetails: "General: GMP (Quantum satis); Infants: 5000 mg/kg; FDA: 0.15% to 3.0%.",
        rawMpl: "GMP",
        unit: "GMP / %",
        regulatorySource: "Codex, JECFA, EU, FDA, Sri Lanka",
        notes: "Lowers pH. Naturally self-limiting due to odor/taste. ADI: 'not limited'.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Lactic Acid",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E270",
        functionalClass: "Acidity regulator, Preservative",
        permittedCategories: "1. Dairy, 2. Beverages, 3. Confectionery/Bakery, 4. Meat surface wash",
        mplDetails: "General: GMP (Quantum satis); Infants: GMP (L+ isomer only); FDA: 0.1% to 2.0%.",
        rawMpl: "GMP",
        unit: "GMP / %",
        regulatorySource: "Codex, JECFA, EU, FDA, Sri Lanka",
        notes: "Smooth tartness. I-isomer restriction for infants. Natural metabolic intermediate.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Dimethyl Dicarbonate (DMDC)",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E242",
        functionalClass: "Preservative / Cold Sterilant",
        permittedCategories: "1. Water-based flavoured drinks, 2. Wines/Ciders, 3. Liquid tea concentrates",
        mplDetails: "Beverages/Teas: 250 mg/kg; Wines: 200 mg/kg (Max added amount).",
        rawMpl: "250",
        unit: "mg/kg / mg/L",
        regulatorySource: "Codex, JECFA, EU, FDA, Sri Lanka",
        notes: "Hydrolyzes in 2-4 hours; zero residue. Toxic in pure form, needs closed-loop dosing.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "2025 / 2026"
    },

    // --- ANTIOXIDANTS ---
    {
        name: "Ascorbic Acid / Vitamin C",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E300",
        functionalClass: "Antioxidant, Colour retention, Flour treatment",
        permittedCategories: "1. Juices/Drinks, 2. Processed meats, 3. Canned fruits/veg, 4. Bakery",
        mplDetails: "General: GMP (Quantum satis); Infants: strictly regulated (e.g. 50 mg/kg in EU).",
        rawMpl: "GMP",
        unit: "GMP / %",
        regulatorySource: "Codex GSFA, JECFA, EU, FDA, Sri Lanka",
        notes: "Risk of benzene with Sodium Benzoate. Inhibits nitrosamines in cured meats.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Sodium Ascorbate",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E301",
        functionalClass: "Antioxidant, Colour retention",
        permittedCategories: "1. Cured meats, 2. Drinks, 3. Canned fruits/veg, 4. Bakery",
        mplDetails: "General: GMP (Quantum satis); FDA: GMP.",
        rawMpl: "GMP",
        unit: "GMP / %",
        regulatorySource: "Codex GSFA, JECFA, EU, FDA, Sri Lanka",
        notes: "Curing accelerator; non-acidic. Preferable where pH stability is required.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Tocopherols / Vitamin E",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E306-309",
        functionalClass: "Antioxidant",
        permittedCategories: "1. Oils/Fats, 2. Infants foods, 3. Cereals/Bakery, 4. Processed meats",
        mplDetails: "Fats/Oils: 300-500 mg/kg; Infants: strictly fixed limits; FDA: 0.01% to 0.05%.",
        rawMpl: "500",
        unit: "mg/kg / %",
        regulatorySource: "Codex GSFA, JECFA, EU, FDA, Sri Lanka",
        notes: "Free radical scavengers. Natural 'clean label' choice. Synergistic with Vitamin C.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Butylated Hydroxyanisole (BHA)",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E320",
        functionalClass: "Antioxidant",
        permittedCategories: "1. Edible fats/oils, 2. Chewing gum, 3. Snacks, 4. Processed meats/potatoes",
        mplDetails: "Fats: 100-200 mg/kg; Gum: 400 mg/kg; FDA: 0.02% of total fat.",
        rawMpl: "200",
        unit: "mg/kg / %",
        regulatorySource: "Codex GSFA, JECFA, EU 1333/2008, FDA, Sri Lanka",
        notes: "Synthetic phenolic. High heat stability. Synergistic with BHT. Under scrutiny (Prop 65).",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Butylated Hydroxytoluene (BHT)",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E321",
        functionalClass: "Antioxidant",
        permittedCategories: "1. Fats/Oils, 2. Chewing gum, 3. Cereals/Snacks, 4. Meats/Potatoes",
        mplDetails: "Fats: 100-200 mg/kg; Snacks: 50 mg/kg; FDA: 0.02% of total fat.",
        rawMpl: "200",
        unit: "mg/kg / %",
        regulatorySource: "Codex, JECFA, EU, FDA, Sri Lanka",
        notes: "Prevents oxidative rancidity. Effective for baked/fried goods. Usually paired with BHA.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Tert-butylhydroquinone (TBHQ)",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E319",
        functionalClass: "Antioxidant",
        permittedCategories: "1. Frying oils, 2. Snacks/Crackers, 3. Processed meats/fish, 4. Popcorn/Noodles",
        mplDetails: "Fats/Oils: 200 mg/kg; FDA: 0.02% of total fat.",
        rawMpl: "200",
        unit: "mg/kg / %",
        regulatorySource: "Codex, JECFA, EU, FDA, Sri Lanka",
        notes: "Industry standard for deep-frying. Exceptional heat stability. Avoid with Propyl Gallate.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "2025 / 2026"
    },
    {
        name: "Calcium Disodium EDTA",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E385",
        functionalClass: "Sequestrant / Antioxidant / Preservative",
        permittedCategories: "1. Mayonnaise/Dressings, 2. Canned veg/legumes, 3. Canned seafood, 4. Fat spreads",
        mplDetails: "Mayonnaise: 75 mg/kg; Beans: 250 mg/kg; Seafood: 250-340 ppm; Spreads: 100 mg/kg.",
        rawMpl: "75",
        unit: "mg/kg / ppm",
        regulatorySource: "Codex, JECFA, EU, FDA, Sri Lanka",
        notes: "Chelating agent. Prevents benzene formation in drinks. Preferred over Disodium EDTA.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "2025 / 2026"
    },

    // --- COLOURS ---
    {
        name: "Curcumin",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E100",
        functionalClass: "Colour",
        permittedCategories: "Confectionery, Sauces, Fats & Oils",
        mplDetails: "GMP / 500 mg/kg",
        rawMpl: "500",
        unit: "mg/kg",
        regulatorySource: "GSFA Table 3, EU 1333/2008, SL Regs",
        notes: "Natural yellow (Turmeric); GMP in most categories.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "14-Nov-25"
    },
    {
        name: "Riboflavins",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E101",
        functionalClass: "Colour",
        permittedCategories: "Dairy products, Cereals, Bakery wares",
        mplDetails: "GMP / 300 mg/kg",
        rawMpl: "300",
        unit: "mg/kg",
        regulatorySource: "GSFA Table 3, FDA 21 CFR §73.450, SL Regs",
        notes: "Vitamin B2 source; Highly heat stable.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "14-Nov-25"
    },
    {
        name: "Tartrazine",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E102",
        functionalClass: "Colour",
        permittedCategories: "Beverages, Sweets, Snacks",
        mplDetails: "100 (SL) / 300 (GSFA)",
        rawMpl: "300",
        unit: "mg/kg",
        regulatorySource: "GSFA, FDA §74.705, SL Regs",
        notes: "Synthetic (Yellow 5); EU warning label required.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Quinoline Yellow",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E104",
        functionalClass: "Colour",
        permittedCategories: "Smoked fish, Seasonings, Edible ices",
        mplDetails: "200 (GSFA)",
        rawMpl: "200",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU, SL Regs",
        notes: "Banned in USA/Canada; Restricted in EU.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "7-Jan-26"
    },
    {
        name: "Sunset Yellow FCF",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E110",
        functionalClass: "Colour",
        permittedCategories: "Breakfast cereals, Dessert, Drinks",
        mplDetails: "100 (SL) / 300 (GSFA)",
        rawMpl: "300",
        unit: "mg/kg",
        regulatorySource: "GSFA, FDA §74.706, SL Regs",
        notes: "Synthetic (Yellow 6); Link to hyperactivity.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Carmoisine",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E122",
        functionalClass: "Colour",
        permittedCategories: "Jams & Jellies, Fruit fillings, Beverages",
        mplDetails: "100 (SL) / 500 (GSFA)",
        rawMpl: "500",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU, SL Regs",
        notes: "Azorubine; Synthetic red; Not permitted in US.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "14-Jan-11"
    },
    {
        name: "Ponceau 4R",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E124",
        functionalClass: "Colour",
        permittedCategories: "Ices & Sherbets, Processed fish, Pastries",
        mplDetails: "100 (SL) / 500 (GSFA)",
        rawMpl: "500",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU, SL Regs",
        notes: "Cochineal Red A; Synthetic azo dye.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "14-Jan-11"
    },
    {
        name: "Erythrosine",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E127",
        functionalClass: "Colour",
        permittedCategories: "Glacé cherries, Cocktail cherries",
        mplDetails: "100 (SL) / 200 (GSFA)",
        rawMpl: "200",
        unit: "mg/kg",
        regulatorySource: "GSFA, FDA §74.303, SL Regs",
        notes: "Synthetic (Red 3); Iodine containing colour.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Allura Red AC",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E129",
        functionalClass: "Colour",
        permittedCategories: "Seasonings, Cereals, Meat products",
        mplDetails: "100 (SL) / 300 (GSFA)",
        rawMpl: "300",
        unit: "mg/kg",
        regulatorySource: "GSFA, FDA §74.340, SL Regs",
        notes: "Synthetic (Red 40); Widely used in US.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Indigotine",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E132",
        functionalClass: "Colour",
        permittedCategories: "Bakery wares, Dairy analogues, Sweets",
        mplDetails: "100 (SL) / 300 (GSFA)",
        rawMpl: "300",
        unit: "mg/kg",
        regulatorySource: "GSFA, FDA §74.102, SL Regs",
        notes: "Indigo Carmine (Blue 2); Synthetic dye.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Brilliant Blue FCF",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E133",
        functionalClass: "Colour",
        permittedCategories: "Dairy desserts, Ices, Soft drinks",
        mplDetails: "100 (SL) / 100 (GSFA)",
        rawMpl: "100",
        unit: "mg/kg",
        regulatorySource: "GSFA, FDA §74.101, SL Regs",
        notes: "Synthetic (Blue 1); Very stable colour.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Chlorophylls",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E140",
        functionalClass: "Colour",
        permittedCategories: "Fats & Oils, Chewing gum, Fruit prep",
        mplDetails: "GMP",
        rawMpl: "GMP",
        unit: "-",
        regulatorySource: "GSFA Table 3, EU 1333/2008, SL Regs",
        notes: "Natural green from plants; Generally safe (GMP).",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Jul-25"
    },
    {
        name: "Copper Chlorophyllins",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E141",
        functionalClass: "Colour",
        permittedCategories: "Canned vegetables, Dairy products, Sauces",
        mplDetails: "500 (GSFA)",
        rawMpl: "500",
        unit: "mg/kg",
        regulatorySource: "GSFA, FDA §73.125, SL Regs",
        notes: "Na/K salts of copper complex; High light stability.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Jul-25"
    },
    {
        name: "Fast Green FCF",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "INS 143",
        functionalClass: "Colour",
        permittedCategories: "Edible ices, Beverages, Desserts",
        mplDetails: "100 (SL) / 100 (GSFA)",
        rawMpl: "100",
        unit: "mg/kg",
        regulatorySource: "GSFA, FDA §74.1203, SL Regs",
        notes: "FD&C Green No. 3; Banned in EU/UK.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Plain Caramel (I)",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E150a",
        functionalClass: "Colour",
        permittedCategories: "Soups & Sauces, Spirits, Bakery wares",
        mplDetails: "GMP",
        rawMpl: "GMP",
        unit: "-",
        regulatorySource: "GSFA Table 3, FDA §73.85, SL Regs",
        notes: "Class I Caramel; No ammonia/sulfite used.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Ammonia Caramel (III)",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E150c",
        functionalClass: "Colour",
        permittedCategories: "Beer, Gravy, Sauces",
        mplDetails: "50,000 (GSFA)",
        rawMpl: "50000",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU, SL Regs",
        notes: "Class III Caramel; Complex brown hue.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Jul-25"
    },
    {
        name: "Brilliant Black BN",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E151",
        functionalClass: "Colour",
        permittedCategories: "Fish roe, Sauces, Sweets",
        mplDetails: "500 (GSFA)",
        rawMpl: "500",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU 1333/2008",
        notes: "Black PN; Synthetic; Not permitted in US.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Jul-25"
    },
    {
        name: "Vegetable Carbon",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E153",
        functionalClass: "Colour",
        permittedCategories: "Cheese, Confectionery, Decorations",
        mplDetails: "GMP",
        rawMpl: "GMP",
        unit: "-",
        regulatorySource: "GSFA Table 3, EU 1333/2008",
        notes: "Activated charcoal; Banned in US as food colour.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Jul-25"
    },
    {
        name: "Brown HT",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E155",
        functionalClass: "Colour",
        permittedCategories: "Chocolate cakes, Biscuits, Dairy",
        mplDetails: "50 (GSFA)",
        rawMpl: "50",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU 1333/2008",
        notes: "Chocolate Brown HT; Synthetic azo dye.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Jul-25"
    },
    {
        name: "Beta-Carotene (Veg)",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E160a",
        functionalClass: "Colour",
        permittedCategories: "Margarine, Fats & Oils, Beverages",
        mplDetails: "1000 (GSFA)",
        rawMpl: "1000",
        unit: "mg/kg",
        regulatorySource: "GSFA, FDA §73.95, SL Regs",
        notes: "Provitamin A source; Natural orange/yellow.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Annatto (Bixin)",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E160b",
        functionalClass: "Colour",
        permittedCategories: "Cheese, Butter, Snacks",
        mplDetails: "1000 (GSFA)",
        rawMpl: "1000",
        unit: "mg/kg",
        regulatorySource: "GSFA, FDA §73.30, SL Regs",
        notes: "Natural seeds extract; Solvent-based extraction.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Paprika Extract",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E160c",
        functionalClass: "Colour",
        permittedCategories: "Snacks, Seasonings, Processed meat",
        mplDetails: "GMP",
        rawMpl: "GMP",
        unit: "-",
        regulatorySource: "GSFA Table 3, FDA §73.340, SL Regs",
        notes: "Natural red pigment; Contains Capsanthin.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Lycopene (Synth)",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E160d",
        functionalClass: "Colour",
        permittedCategories: "Sauces, Beverages, Desserts",
        mplDetails: "5000 (GSFA)",
        rawMpl: "5000",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU, FDA §73.585",
        notes: "Tomato-like red hue; High antioxidant capacity.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Beetroot Red",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E162",
        functionalClass: "Colour",
        permittedCategories: "Yogurt, Meat products, Ices",
        mplDetails: "GMP",
        rawMpl: "GMP",
        unit: "-",
        regulatorySource: "GSFA Table 3, FDA §73.40, SL Regs",
        notes: "Betanin from beets; pH and heat sensitive.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Anthocyanins",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E163",
        functionalClass: "Colour",
        permittedCategories: "Beverages, Fruit prep, Confectionery",
        mplDetails: "GMP",
        rawMpl: "GMP",
        unit: "-",
        regulatorySource: "GSFA Table 3, FDA §73.170, SL Regs",
        notes: "From grape skins/veg; pH sensitive (red-blue).",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Mar-26"
    },

    // --- EMULSIFIERS ---
    {
        name: "Lecithin",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E322",
        functionalClass: "Emulsifier, antioxidant",
        permittedCategories: "Chocolate, biscuit, bakery products, salad dressing",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex GSFA, FDA §184.1400, EU",
        notes: "Allergen warning (Soy/Egg). Minimal long-term high-dose data.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Mono and diglyceride of fatty acid",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E471",
        functionalClass: "Emulsifier",
        permittedCategories: "Bakery, ice cream, margarine, cake, biscuit",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex GSFA, FDA (GRAS), EU",
        notes: "GRAS. Plant or animal derived. Rare sensitivity.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Polysorbates",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E433 (E434,E435,E436)",
        functionalClass: "Emulsifier",
        permittedCategories: "Ice cream, baked product",
        mplDetails: "0.5 - 1.0 %",
        rawMpl: "1",
        unit: "%",
        regulatorySource: "Codex, FDA §172.840, EU",
        notes: "Synthetic origin. May cause mild digestive sensitivity.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Datem",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E472e",
        functionalClass: "Emulsifier",
        permittedCategories: "Bread, cake, processed dough",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA, EU",
        notes: "Synthetic emulsifier with usage limits. Rare sensitivity.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Carrageenan",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E407",
        functionalClass: "Emulsifier, thickener",
        permittedCategories: "Dairy products",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA, EU",
        notes: "Controversial (digestive concerns). EFSA opinion 2018.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "2018 / 2025"
    },
    {
        name: "Guar gum",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E412",
        functionalClass: "Emulsifier, thickener",
        permittedCategories: "Sauce, beverage, dessert",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA (GRAS), EU",
        notes: "May cause bloating in high amounts. Generally safe.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Gum arabic",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E414",
        functionalClass: "Emulsifier, stabilizer",
        permittedCategories: "Confectionary beverages",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA (GRAS), EU",
        notes: "Rare allergic reactions. Generally well tolerated.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Xanthan gum",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E415",
        functionalClass: "Emulsifier, thickener",
        permittedCategories: "Sauce, bakery products",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA (GRAS), EU",
        notes: "Possible digestive discomfort in excess. Safe usage levels.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Sodium stearoyl-2 lactylate",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E481",
        functionalClass: "Emulsifier",
        permittedCategories: "Bakery products",
        mplDetails: "0.5 %",
        rawMpl: "0.5",
        unit: "%",
        regulatorySource: "Codex, FDA §172.846, EU",
        notes: "Approved emulsifier with limits. Rare sensitivity case.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Glucerol monostearate",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E471",
        functionalClass: "Emulsifier",
        permittedCategories: "Bakery products, ice cream",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA (GRAS), EU",
        notes: "Generally safe. May be animal- or plant-derived.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Sucrose esters of fatty acids",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E473",
        functionalClass: "Emulsifier",
        permittedCategories: "Bakery, dairy products",
        mplDetails: "1 %",
        rawMpl: "1",
        unit: "%",
        regulatorySource: "Codex, FDA (GRAS), EU",
        notes: "Regulated usage limits. Low toxicity.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Polyglycerol esters of fatty acids",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E475",
        functionalClass: "Emulsifier",
        permittedCategories: "Chocolate, baked products",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA, EU",
        notes: "Approved within limits. Minimal toxicity concerns.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Sorbitan monostearate",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E491",
        functionalClass: "Emulsifier",
        permittedCategories: "Bakery, confectionary",
        mplDetails: "0.5 %",
        rawMpl: "0.5",
        unit: "%",
        regulatorySource: "Codex, FDA §172.842, EU",
        notes: "Safe within limits. May cause mild digestive effects.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Sodium Caseinates",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E469",
        functionalClass: "Emulsifier, stabilizer",
        permittedCategories: "Dairy products, processed foods",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA (GRAS), EU",
        notes: "Milk-derived allergen. Not suitable for dairy-free.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Ammonium phosphatides",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E442",
        functionalClass: "Emulsifier",
        permittedCategories: "Chocolate, cocoa products",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA, EU",
        notes: "Approved emulsifier for chocolate. Usage limits apply.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Hydroxypropyl methyl cellulose",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E464",
        functionalClass: "Emulsifier, thickener",
        permittedCategories: "Bakery, sauces",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA (GRAS), EU",
        notes: "Cellulose derivative. Generally safe.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Methyl cellulose",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E461",
        functionalClass: "Emulsifier, thickener",
        permittedCategories: "Processed foods",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA (GRAS), EU",
        notes: "Safe at food levels. Possible bloating.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Stearyl tartrate",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E483",
        functionalClass: "Emulsifier",
        permittedCategories: "Bakery, dough products",
        mplDetails: "0.5 %",
        rawMpl: "0.5",
        unit: "%",
        regulatorySource: "Codex, FDA, EU",
        notes: "Approved with limits. Minimal toxicity.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Gellan gum",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E418",
        functionalClass: "Emulsifier, stabilizer",
        permittedCategories: "Beverages",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA (GRAS), EU",
        notes: "Generally safe. Rare digestive sensitivity.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Sucroglycerides",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E474",
        functionalClass: "Emulsifier",
        permittedCategories: "Bakery, confectionary",
        mplDetails: "1 %",
        rawMpl: "1",
        unit: "%",
        regulatorySource: "Codex, FDA, EU",
        notes: "Low toxicity at permitted levels.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Propylene glycol esters of fatty acids",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E477",
        functionalClass: "Emulsifier",
        permittedCategories: "Sauce",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA, EU",
        notes: "Regulated additive. Generally safe.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Calcium stearoyl lactylate",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E482",
        functionalClass: "Emulsifier",
        permittedCategories: "Processed foods",
        mplDetails: "0.5 %",
        rawMpl: "0.5",
        unit: "%",
        regulatorySource: "Codex, FDA §172.844, EU",
        notes: "Approved with limits. Rare sensitivity.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Polyphosphate",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E452",
        functionalClass: "Emulsifier, stabilizer",
        permittedCategories: "Processed meat, seafood",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA, EU",
        notes: "Excess may affect mineral balance. Regulated usage.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Polyglycerol polyricinoleate (PGPR)",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E476",
        functionalClass: "Emulsifier",
        permittedCategories: "Chocolate, fat spread",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA, EU",
        notes: "Standard chocolate emulsifier. Limited concerns.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Propylene glycol alginate",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E405",
        functionalClass: "Emulsifier, stabilizer",
        permittedCategories: "Sauce, beverage, bakery",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex, FDA (GRAS), EU",
        notes: "Approved additive. Generally safe within limits.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },

    // --- ANTIOXIDANTS (CONT.) ---
    {
        name: "Citric acid",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E330",
        functionalClass: "Antioxidant, Acidity regulator",
        permittedCategories: "Canned foods, beverages",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex GSFA, FDA §184.1033, EU",
        notes: "Generally safe. Excess may contribute to dental erosion.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Propyl gallate",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E310",
        functionalClass: "Antioxidant",
        permittedCategories: "Snack foods, fats, oils",
        mplDetails: "0.01%",
        rawMpl: "0.01",
        unit: "%",
        regulatorySource: "Codex GSFA, FDA §172.615",
        notes: "Approved antioxidant. Rare sensitivity reported.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Ascorbyl palmitate",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E304",
        functionalClass: "Antioxidant",
        permittedCategories: "Fats, oils",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex GSFA, FDA §182.3149, EU",
        notes: "Fat-soluble derivative of vitamin C. Generally safe.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Rosemary extract",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E392",
        functionalClass: "Antioxidant",
        permittedCategories: "Vegetable Oils, margarine, meat",
        mplDetails: "0.01%",
        rawMpl: "0.01",
        unit: "%",
        regulatorySource: "Codex, FDA (GRAS), EU",
        notes: "Natural extract. Possible mild allergic reactions in some.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Erythorbic acid",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E315",
        functionalClass: "Antioxidant",
        permittedCategories: "Meat, canned foods",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex GSFA, FDA §182.3045, EU",
        notes: "Structurally related to Vitamin C but not a vitamin.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Alpha tocopherol",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E307",
        functionalClass: "Antioxidant",
        permittedCategories: "Vegetable oil",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex GSFA, FDA §182.8890, EU",
        notes: "Safe at typical levels. Form of Vitamin E.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Octyl gallate",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E311",
        functionalClass: "Antioxidant",
        permittedCategories: "Fats, oil",
        mplDetails: "0.01%",
        rawMpl: "0.01",
        unit: "%",
        regulatorySource: "Codex GSFA, EU, FDA",
        notes: "Possible rare sensitivity reactions.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Dodecyl gallate",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E312",
        functionalClass: "Antioxidant",
        permittedCategories: "Fat emulsions",
        mplDetails: "0.01%",
        rawMpl: "0.01",
        unit: "%",
        regulatorySource: "Codex GSFA, EU, FDA",
        notes: "Rare allergic reactions reported.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },
    {
        name: "Tartaric acid",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E334",
        functionalClass: "Antioxidant, acidulant",
        permittedCategories: "Fruit products, beverages",
        mplDetails: "According to GMP",
        rawMpl: "GMP",
        unit: "%",
        regulatorySource: "Codex GSFA, FDA §184.1099, EU",
        notes: "Naturally occurring. High intake may cause discomfort.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "June 2025"
    },

    // --- STABILIZERS ---
    {
        name: "Pectin",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E440",
        functionalClass: "Stabilizer, Gelling agent",
        permittedCategories: "Jams, yoghurt, beverages",
        mplDetails: "GMP",
        rawMpl: "GMP",
        unit: "-",
        regulatorySource: "GSFA, EU 1333/2008, SL Regs",
        notes: "Natural (fruit-based). High degree of gelation.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "14-Nov-25"
    },
    {
        name: "Agar",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E406",
        functionalClass: "Stabilizer, Thickener",
        permittedCategories: "Desserts, jellies, dairy",
        mplDetails: "GMP",
        rawMpl: "GMP",
        unit: "-",
        regulatorySource: "GSFA, EU, SL",
        notes: "Seaweed origin. Strong gel formation.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Jul-25"
    },
    {
        name: "Carrageenan",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E407",
        functionalClass: "Stabilizer, Thickener",
        permittedCategories: "Milk, ice cream, meat",
        mplDetails: "1000 mg/kg",
        rawMpl: "1000",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU, FDA",
        notes: "May cause sensitivity in excess.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Jul-25"
    },
    {
        name: "Locust Bean Gum",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E410",
        functionalClass: "Stabilizer, Thickener",
        permittedCategories: "Ice cream, dairy, sauces",
        mplDetails: "5000 mg/kg",
        rawMpl: "5000",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU",
        notes: "Works synergistically with carrageenan.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Jul-25"
    },
    {
        name: "Xanthan Gum",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E415",
        functionalClass: "Stabilizer, Thickener",
        permittedCategories: "Dressings, beverages, gluten-free",
        mplDetails: "1000 mg/kg",
        rawMpl: "1000",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU, FDA",
        notes: "Highly stable at wide pH and temperature ranges.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Gum Arabic",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E414",
        functionalClass: "Stabilizer, Emulsifier",
        permittedCategories: "Soft drinks, confectionery",
        mplDetails: "10000 mg/kg",
        rawMpl: "10000",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU",
        notes: "Acacia tree source. Excellent stabilizer.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Jul-25"
    },
    {
        name: "Sodium Alginate",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E401",
        functionalClass: "Stabilizer, Gelling agent",
        permittedCategories: "Ice cream, sauces",
        mplDetails: "1000 mg/kg",
        rawMpl: "1000",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU",
        notes: "Forms gel with calcium ions.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Jul-25"
    },
    {
        name: "Gelatin",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "INS 441",
        functionalClass: "Stabilizer, Gelling agent",
        permittedCategories: "Desserts, dairy, confectionery",
        mplDetails: "GMP",
        rawMpl: "GMP",
        unit: "-",
        regulatorySource: "GSFA, FDA",
        notes: "Animal origin protein.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Modified Starch",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E1404–E1450",
        functionalClass: "Stabilizer, Thickener",
        permittedCategories: "Soups, sauces, dairy",
        mplDetails: "20,000 mg/kg",
        rawMpl: "20000",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU",
        notes: "Chemically modified starch for texture.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Carboxymethyl Cellulose (CMC)",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E466",
        functionalClass: "Stabilizer, Thickener",
        permittedCategories: "Ice cream, bakery, beverages",
        mplDetails: "10,000 mg/kg",
        rawMpl: "10000",
        unit: "mg/kg",
        regulatorySource: "GSFA, FDA",
        notes: "Prevents ice crystal formation in frozen foods.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Konjac Gum",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E425",
        functionalClass: "Stabilizer, Thickener",
        permittedCategories: "Noodles, jelly, vegan foods",
        mplDetails: "10,000 mg/kg",
        rawMpl: "10000",
        unit: "mg/kg",
        regulatorySource: "GSFA",
        notes: "High water absorption capacity.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Mar-26"
    },
    {
        name: "Calcium Alginate",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E404",
        functionalClass: "Stabilizer, Gelling agent",
        permittedCategories: "Reformed foods, desserts",
        mplDetails: "1000 mg/kg",
        rawMpl: "1000",
        unit: "mg/kg",
        regulatorySource: "GSFA, EU",
        notes: "Used in molecular gastronomy.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Jul-25"
    },
    {
        name: "Potassium Alginate",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E402",
        functionalClass: "Stabilizer",
        permittedCategories: "Dairy, desserts",
        mplDetails: "1000 mg/kg",
        rawMpl: "1000",
        unit: "mg/kg",
        regulatorySource: "GSFA",
        notes: "Similar to sodium alginate.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Jul-25"
    },
    {
        name: "Tragacanth",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E413",
        functionalClass: "Stabilizer, Thickener",
        permittedCategories: "Sauces, dressings",
        mplDetails: "10,000 mg/kg",
        rawMpl: "10000",
        unit: "mg/kg",
        regulatorySource: "GSFA",
        notes: "Natural gum, expensive.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "7-Jan-26"
    },
    {
        name: "Tara Gum",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E417",
        functionalClass: "Stabilizer",
        permittedCategories: "Dairy, desserts",
        mplDetails: "5000 mg/kg",
        rawMpl: "5000",
        unit: "mg/kg",
        regulatorySource: "GSFA",
        notes: "Alternative to guar gum.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "7-Jan-26"
    },
    {
        name: "Microcrystalline Cellulose",
        image: "images/ingredients/sodium_benzoate.jpg",
        ins: "E460",
        functionalClass: "Stabilizer, Bulking agent",
        permittedCategories: "Low-fat foods, dairy",
        mplDetails: "GMP",
        rawMpl: "GMP",
        unit: "-",
        regulatorySource: "GSFA, FDA",
        notes: "Fat replacer.",
        regulatorySourceDetailed: "will be added soon...",
        notesRestrictions: "will be added soon...",
        sideEffects: "will be added soon...",
        concerns: "will be added soon...",
        lastUpdated: "16-Mar-26"
    }
];
